# Generated by Django 2.2.5 on 2019-10-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191010_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uv',
        ),
    ]
